#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

compose() {
  docker compose "$@"
}

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

read_env() {
  local key="$1"
  grep -E "^${key}=" .env 2>/dev/null | tail -1 | cut -d= -f2- || true
}

wait_container_healthy() {
  local service="$1"
  local timeout="${2:-120}"
  local cid status elapsed=0
  cid="$(compose ps -q "$service")"
  if [[ -z "$cid" ]]; then
    echo "No container for service $service" >&2
    return 1
  fi
  while (( elapsed < timeout )); do
    status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid")"
    if [[ "$status" == "healthy" || "$status" == "running" && "$service" == "worker" ]]; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo "Service $service did not become healthy in ${timeout}s" >&2
  compose logs --tail=120 "$service" >&2 || true
  return 1
}

wait_http() {
  local url="$1"
  local timeout="${2:-120}"
  local elapsed=0
  while (( elapsed < timeout )); do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo "HTTP endpoint did not become ready: $url" >&2
  compose logs --tail=120 api >&2 || true
  return 1
}

install_hermes_provider_if_requested() {
  local mode="${SIQUEIRA_INSTALL_HERMES_PROVIDER:-auto}"
  local hermes_home="${HERMES_HOME:-$HOME/.hermes}"
  local config_path="${HERMES_CONFIG_PATH:-$hermes_home/config.yaml}"

  case "$mode" in
    0|false|False|no|NO|skip|disabled)
      echo "Skipping Hermes MemoryProvider install (SIQUEIRA_INSTALL_HERMES_PROVIDER=$mode)."
      return 0
      ;;
    1|true|True|yes|YES|force)
      ;;
    auto|"")
      if ! command -v hermes >/dev/null 2>&1; then
        echo "Hermes binary not found; skipping Hermes MemoryProvider install."
        echo "Run ./scripts/install_hermes_provider.sh later on the Hermes host."
        return 0
      fi
      if [[ ! -f "$config_path" ]]; then
        echo "Hermes config not found at $config_path; skipping Hermes MemoryProvider install."
        echo "Run ./scripts/install_hermes_provider.sh after Hermes is configured."
        return 0
      fi
      ;;
    *)
      echo "Unsupported SIQUEIRA_INSTALL_HERMES_PROVIDER=$mode (use auto/true/false)." >&2
      return 1
      ;;
  esac

  echo "Installing Siqueira as the active Hermes MemoryProvider..."
  "$ROOT/scripts/install_hermes_provider.sh"
}

main() {
  need docker
  need curl
  need python3

  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose v2 is required: install Docker Desktop or docker-compose-plugin." >&2
    exit 1
  fi

  if [[ ! -f .env ]]; then
    cat > .env <<EOF
# Generated by scripts/bootstrap.sh. Safe to edit; do not commit.
SIQUEIRA_ENV=development
SIQUEIRA_PUBLIC_PORT=8787
SIQUEIRA_POSTGRES_PORT=5432
SIQUEIRA_REDIS_PORT=6379
POSTGRES_USER=siqueira
POSTGRES_DB=siqueira_memo
POSTGRES_PASSWORD=$(secret)
SIQUEIRA_API_TOKEN=$(secret)
SIQUEIRA_EMBEDDING_PROVIDER=mock
SIQUEIRA_EMBEDDING_MODEL=text-embedding-3-large
SIQUEIRA_EMBEDDING_DIMS=3072
SIQUEIRA_RERANKER_PROVIDER=mock
SIQUEIRA_LOG_LEVEL=INFO
SIQUEIRA_OTEL_ENABLED=false
EOF
    chmod 600 .env
    echo "Created .env with generated local secrets."
  else
    echo ".env already exists; preserving it."
  fi

  echo "Validating compose file..."
  compose config >/dev/null

  echo "Pulling base services..."
  compose pull postgres redis

  echo "Building Siqueira Memo image..."
  compose build api worker migrate

  echo "Starting Postgres + Redis..."
  compose up -d postgres redis
  wait_container_healthy postgres 180
  wait_container_healthy redis 120

  echo "Running Alembic migrations..."
  compose --profile ops run --rm migrate

  echo "Starting API + worker..."
  compose up -d api worker
  wait_container_healthy api 180
  wait_http "http://127.0.0.1:$(read_env SIQUEIRA_PUBLIC_PORT)/healthz" 120

  echo "Smoke-checking readiness..."
  curl -fsS "http://127.0.0.1:$(read_env SIQUEIRA_PUBLIC_PORT)/readyz" | python3 -m json.tool

  install_hermes_provider_if_requested

  cat <<EOF

Siqueira Memo is up.

API:      http://127.0.0.1:$(read_env SIQUEIRA_PUBLIC_PORT)
Health:   http://127.0.0.1:$(read_env SIQUEIRA_PUBLIC_PORT)/healthz
Ready:    http://127.0.0.1:$(read_env SIQUEIRA_PUBLIC_PORT)/readyz
Token:    stored in .env as SIQUEIRA_API_TOKEN

Useful commands:
  docker compose ps
  docker compose logs -f api worker
  docker compose down
  docker compose down -v  # destructive: removes Postgres volume
EOF
}

main "$@"
